# Generated by Django 2.0.13 on 2019-05-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190514_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='childtable',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.PlayerTable'),
        ),
    ]
